project:
  type: website

website:
  title: "Your Health In Data"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/ignacio-zamora-quiroz-783a05208/
format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly

editor: visual

comments:
  giscus:
    repo: IgnacioZQ/Your-Health-In-Data